spring.application.name=SpringWebProject
spring.datasource.url=jdbc:mysql://localhost:3306/mobileShop_db
spring.datasource.username=root
spring.datasource.password=root
server.port=8081


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mkhantkyaw899@gmail.com
spring.mail.password=ytey fmsj azli wcke
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true